### ISSUE TITLE
Info section doesn't show 

### ISSUE THREAD

**Issue by thibaultdvx** [aramis-lab/clinicadl_handbook#18]
https://github.com/aramis-lab/clinicadl_handbook/blob/9b30382d68f0ff356589cd4cfdcace1154ba8f61/notebooks/preprocessing.ipynb#L321-L329

Those lines don't show in: 

https://aramislab.paris.inria.fr/clinicadl/tuto/2023/html/notebooks/preprocessing.html

**Comment by NicolasGensollen** [comment]
Good catch ! Seems to be the case also for:

```
{info}
You need to have performed the t1-linear pipeline on your T1-weighted MR images.
```

**Comment by thibaultdvx** [comment]
Any idea why?

**Comment by NicolasGensollen** [comment]
> Any idea why?

Nope, I don't see anything problematic and the warning blocks seem to work as expected... 🤔 
Maybe we could try to replace "info" with "note" to see if it works better (see the doc of jupyterbook [here](https://jupyterbook.org/en/stable/content/myst.html#content-myst-directives)).

**Comment by thibaultdvx** [comment]
Yes I will try, but how is it possible to have a preview before the PR is merged to main?

**Comment by thibaultdvx** [comment]
Ok thanks!
