### ISSUE TITLE
Incorrect file suffix

### ISSUE THREAD

**Issue by thibaultdvx** [aramis-lab/clinicadl_handbook#19]
https://github.com/aramis-lab/clinicadl_handbook/blob/9b30382d68f0ff356589cd4cfdcace1154ba8f61/notebooks/preprocessing.ipynb#L426

The right suffix is `_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.nii.gz`, as mentioned few lines above (line 363).

**Comment by NicolasGensollen** [comment]
Yes good catch ! This was changed a few months ago in Clinica in order to be more BIDS-compliant.
"T1w" is the suffix and should only appear at the end of the file name, just before the extension.
