### ISSUE TITLE
Doubts on the statistical analysis

### ISSUE THREAD

**Issue by thibaultdvx** [aramis-lab/clinicadl_handbook#28]
https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L273-L286

But the results of `tsvtools analysis` are:

![Capture d’écran 2024-03-14 à 12 35 48](https://github.com/aramis-lab/clinicadl_handbook/assets/154365476/c786bbdf-dc4e-4082-ba72-b91f6bdfc7a3)

The bias is on age rather than sex, isn't it?

**Comment by thibaultdvx** [comment]
https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L208-L209

It is mentioned that youngest participants have been excluded, but I can't find any mention of this operation before this section.

**Comment by NicolasGensollen** [comment]
@nburgos what do you think about this ?
I'm a bit hesitant to approve #34 which changes the interpretation of the results.

**Comment by nburgos** [comment]
The part where we exclude CN subjects younger than 62 years (the minimum age of the AD subjects) is done live with the participants when we do the practicals. I guess this explains why it is missing here. I would add this step and keep the scenario as it was.

**Comment by thibaultdvx** [comment]
Thanks @nburgos! I just did what you suggested in #34
